BUNDLES = [
    '//apps/p4int/intmgr:onos-apps-p4int-intmgr',
]

onos_app(
    title = 'P4 In-band Network Telemetry Service',
    description = 'Provides managements of INT-capable devices. Specifies flows to enable INT and' +
    'types of metadata to collect. Sets up INT-related information.',
    category = 'Monitoring',
    included_bundles = BUNDLES,
)
